package com.deliveryhub.uberwatcher.material.tokens

internal object OutlinedButtonTokens {
    val DisabledContainerOpacity = 0.1f
    val DisabledIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val DisabledIconOpacity = 0.38f
    val DisabledLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val DisabledLabelTextOpacity = 0.38f
    val DisabledOutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val FocusedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val FocusedLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val FocusedOutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val HoveredIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val HoveredLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val HoveredOutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val IconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val LabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val OutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val PressedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val PressedLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val PressedOutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val SelectedContainerColor = ColorSchemeKeyTokens.InverseSurface
    val SelectedDisabledContainerColor = ColorSchemeKeyTokens.OnSurface
    val SelectedFocusedIconColor = ColorSchemeKeyTokens.InverseOnSurface
    val SelectedFocusedLabelTextColor = ColorSchemeKeyTokens.InverseOnSurface
    val SelectedHoveredIconColor = ColorSchemeKeyTokens.InverseOnSurface
    val SelectedHoveredLabelTextColor = ColorSchemeKeyTokens.InverseOnSurface
    val SelectedIconColor = ColorSchemeKeyTokens.InverseOnSurface
    val SelectedLabelTextColor = ColorSchemeKeyTokens.InverseOnSurface
    val SelectedPressedIconColor = ColorSchemeKeyTokens.InverseOnSurface
    val SelectedPressedLabelTextColor = ColorSchemeKeyTokens.InverseOnSurface
    val UnselectedDisabledOutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val UnselectedFocusedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedFocusedLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedFocusedOutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val UnselectedHoveredIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedHoveredLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedHoveredOutlineColor = ColorSchemeKeyTokens.OutlineVariant
    val UnselectedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedPressedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedPressedLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedPressedOutlineColor = ColorSchemeKeyTokens.OutlineVariant
}